version = 1
name = "Server"

[setup]
script = ""

[[actions]]
name = "启动Server"
icon = "run"
command = '''
powershell -ExecutionPolicy Bypass -File D:\UGitD\LockStep\LockStepDemo\Server\scripts\start-server.ps1
'''
