//----------------------------------------------------------
// <auto-generated>
// -This code was generated.
// -Changes to this file may cause incorrect behavior.
// -will be lost if the code is regenerated.
// <auto-generated/>
//----------------------------------------------------------
using TMPro;
using UnityEngine;
using UnityEngine.UI;
using TEngine;

namespace GameLogic
{
    public partial class UISample : UIWindow
    {
        #region 脚本工具生成的代码

        private UIBindComponent m_bindComponent;
        private Slider m_sliderHour_ = null!;
        private TextMeshProUGUI m_tmpHour_ = null!;
        private TextMeshProUGUI m_tmpDate_ = null!;
        private TextMeshProUGUI m_tmpWeather_ = null!;
        private TextMeshProUGUI m_tmpSeason_ = null!;
        private TextMeshProUGUI m_tmpTemperature_ = null!;
        private TextMeshProUGUI m_tmpWetness_ = null!;
        private TextMeshProUGUI m_tmpSnow_ = null!;
        private TextMeshProUGUI m_tmpQuality_ = null!;
        private Button m_btnQualityNext_ = null!;
        private Button m_btnWeatherNext_ = null!;
        private Toggle m_toggleSimulation_ = null!;

        protected override void ScriptGenerator()
        {
            m_bindComponent = gameObject.GetComponent<UIBindComponent>();
            if (m_bindComponent == null)
            {
                Log.Error($"根物体: {gameObject.name} 缺少组件 UIBindComponent, 请检查！");
                return;
            }
            m_sliderHour_ = m_bindComponent.GetComponent<Slider>(0);
            m_tmpHour_ = m_bindComponent.GetComponent<TextMeshProUGUI>(1);
            m_tmpDate_ = m_bindComponent.GetComponent<TextMeshProUGUI>(2);
            m_tmpWeather_ = m_bindComponent.GetComponent<TextMeshProUGUI>(3);
            m_tmpSeason_ = m_bindComponent.GetComponent<TextMeshProUGUI>(4);
            m_tmpTemperature_ = m_bindComponent.GetComponent<TextMeshProUGUI>(5);
            m_tmpWetness_ = m_bindComponent.GetComponent<TextMeshProUGUI>(6);
            m_tmpSnow_ = m_bindComponent.GetComponent<TextMeshProUGUI>(7);
            m_tmpQuality_ = m_bindComponent.GetComponent<TextMeshProUGUI>(8);
            m_btnQualityNext_ = m_bindComponent.GetComponent<Button>(9);
            m_btnWeatherNext_ = m_bindComponent.GetComponent<Button>(10);
            m_toggleSimulation_ = m_bindComponent.GetComponent<Toggle>(11);
        }

        #endregion

        #region 事件

        private partial void OnHourSliderChanged(float value);
        private partial void OnQualityNextClicked();
        private partial void OnWeatherNextClicked();
        private partial void OnSimulationToggled(bool isOn);

        #endregion
    }
}
